a=int(input("Enter an integer: "))
b=int(input("Enter another integer: "))
print("The sum of the two integers was:", a +b)
print("The difference of the two integers was:", a - b)
print("The product of the two integers was:", a * b)
print("The quotient of the two integers was:", a / b)
print("The remainder of the two integers was:", a % b)
print("The integer division of the two integers was:", a // b)
print("The exponent of the two integers was:", a ** b)
print("The absolute value of the first integer was:", abs(a))
print("The absolute value of the second integer was:", abs(b))
print("The maximum of the two integers was:", max(a, b))
print("The minimum of the two integers was:", min(a, b))
print("The average of the two integers was:", (a + b) / 2)