a=int(input("Enter an integer: "))
b=int(input("Enter another integer: "))
print("The sum of the two integers was:", a +b)
print("The difference of the two integers was:", a - b)
print("The product of the two integers was:", a * b)
print("The quotient of the two integers was:", a / b)