a=int(input("Enter an integer: "))
b=int(input("Enter another integer: "))
print("The sum of the two integers was:", a +b)
print("The difference of the two integers was:", a - b)
print("The product of the two integers was:", a * b)
print("The quotient of the two integers was:", a / b)
print("The remainder of the two integers was:", a % b)
print("The integer division of the two integers was:", a // b)
print("The exponent of the two integers was:", a ** b)
print("The absolute value of the first integer was:", abs(a))
print("The absolute value of the second integer was:", abs(b))
print("The maximum of the two integers was:", max(a, b))
print("The minimum of the two integers was:", min(a, b))
print("The average of the two integers was:", (a + b) / 2)
c=int(input("Enter a third integer: "))
print("The sum of the three integers was:", a + b + c)
print("The product of the three integers was:", a * b * c)
print("The average of the three integers was:", (a + b + c) / 3)
print("The maximum of the three integers was:", max(a, b, c))
print("The minimum of the three integers was:", min(a, b, c))
print("The absolute value of the third integer was:", abs(c))
print("The sum of the squares of the three integers was:", a**2 + b**2 + c**2)
print("The sum of the cubes of the three integers was:", a**3 + b**3 + c**3)
print("The sum of the fourth powers of the three integers was:", a**4 + b**4 + c**4)
print("The sum of the fifth powers of the three integers was:", a**5 + b**5 + c**5)
print("The sum of the sixth powers of the three integers was:", a**6 + b**6 + c**6)
print("The sum of the seventh powers of the three integers was:", a**7 + b**7 + c**7)